version: "3.4"

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    restart: always
    labels:
      NAME: "rabbitmq"
    ports:
      - "15672:15672"
      - "5672:5672"
    expose:
      - "5672"
    networks:
      - default
 